### ISSUE TITLE
mediafile version

### ISSUE THREAD

**Issue by arogl** [gtronset/beets-filetote#132]
@gtronset any reason mediafile is locked at 0.10.0 in the [requirements.txt](https://github.com/gtronset/beets-filetote/blob/main/requirements.txt#L3) file?

Version 0.12.0 has been released [pypi release](https://pypi.org/project/mediafile/)

**Comment by gtronset** [comment]
This was corrected in https://github.com/gtronset/beets-filetote/pull/134 and will be in the next Filetote version.
