### ISSUE TITLE
Missing [project] in pyproject.toml

### ISSUE THREAD

**Issue by dansbandit** [gtronset/beets-filetote#135]
Building in nix results in this error https://github.com/pypa/setuptools/issues/3197 due to the upgraded version of setuptools. This can be fixed by adding the following to `pyproject.toml` as per https://stackoverflow.com/questions/76652773/how-to-fix-configuration-error-project-must-contain-name-properties-in
```
[project]
name = 'project name'
requires-python = ">=3.9"
version = "1.0.0"
authors = [
    {name = "Your Name", email = "you@yourdomain.com"},
]
```
Thanks for creating this software!

**Comment by gtronset** [comment]
@dansbandit thanks for the issue and comment about how you resolved it. This plugin switched to using Poetry for builds, but the documentation is a bit outdated for devs and there is some clutter that I'm working to resolve in a PR soon.
