### ISSUE TITLE
Update beets version requirement

### ISSUE THREAD

**Issue by boredness** [gtronset/beets-filetote#153]
Hello,

Thanks for actively maintaining this plugin as i'm hoping to move to it from the other older unmaintained options. 

Issue i'm facing is that since this requires beets version 1.6.0 it still contains huge bugs like this: https://github.com/beetbox/beets/issues/4528 which has been fixed and can be used with beets-git for example but hasn't had a full release of beets yet.

Can you allow versions which equal that or higher? or any way to not even require a version if possible

Thank you.

* OS: Arch
* Python version: 3.11.8
* beets version: 1.6.0
* Filetote version: 0.4.6

**Comment by swills1** [comment]
I'm currently looking for an extrafiles replacement and am reading through the code and info on Filetote. Maybe i am missing something, but the `pyproject.toml` requires `1.6.0` or higher. Line 25 - `beets = "^1.6.0"`.

Is there a specific issue you're facing or do you just have a concern? the current stable release of Beets is 1.6.0.

**Comment by swills1** [comment]
I'm currently looking for an extrafiles replacement and am reading through the code and info on Filetote for the first time. So maybe I am missing something, but the `pyproject.toml` requires `1.6.0` or higher. Line 25 - `beets = "^1.6.0"`.

Is there a specific issue you're facing or do you just have a concern? the current stable release of Beets is 1.6.0.

**Comment by swills1** [comment]
I'm currently looking for an extrafiles replacement and am reading through the code and info on Filetote for the first time. So maybe I am missing something, but the `pyproject.toml` requires `1.6.0` or higher. Line 25 - `beets = "^1.6.0"`.

Is there a specific issue you're facing or do you just have a concern? The current stable release of Beets is 1.6.0.

**Comment by gtronset** [comment]
@boredness @swills1 `v0.4.9` is now out and should resolve this.

**Comment by swills1** [comment]
For what it's worth, I feel a more accurate description of this issue would have been - "Allow beets-filetote to work with versions of Beets newer than the official stable version". Glad it's working now. Thanks.
