### ISSUE TITLE
File stat error

### ISSUE THREAD

**Issue by arogl** [gtronset/beets-filetote#99]
```log
beet imp .                                                                                                                                                                                    in cmd at 18:26:24
Import of the directory:
I:\New_Music\import
was interrupted. Resume (Y/n)?
Resuming interrupted import of I:\New_Music\import

I:\New_Music\import\Emily Brooke\Easy on Me (1 items)
Tagging:
    Emily Brooke - Easy on Me
URL:
    https://www.deezer.com/album/212302112
(Similarity: 96.0%) (source, tracks) (Deezer, 2021, Emily Brooke)
 * Easy on Me -> Easy on Me (source)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates?
could not get filesize: [WinError 2] The system cannot find the file specified: '\\\\?\\I:\\New_Music\\import\\Emily Brooke\\Easy on Me\\01 - Easy on Me.mp3'
```

Disabling `filetote` I do not get the error.

Sometimes `filetote` no longer moves the `.lrc` files either.

Both the music and lyric fille have the same name except for the extension.

Small debug shows the error is in this call [beets/library.py](https://github.com/beetbox/beets/blob/master/beets/library.py#L888-898)

Still to look at why/how `filetote` is calling that function `_getters` with the old file

**Comment by arogl** [comment]
I have confirmed that the files are moved, but all moved at the end of the process.

I was looking for the files to be moved as part of the original move.

**Comment by gtronset** [comment]
@arogl thank you for letting me know about the filesize error. I think that's more of a warning in this context, but I'll dig into it to see if I can prevent it from occurring.

You are correct that the files are moved at the end of the process, at `cli_exit`. This is also true of the other related plugins (`extrafiles`, etc.). I might be able to make that configurable, but that'll take some time to investigate to see, and may reduce functionality.

Regarding the error/warning: at a high level, the functions that give access to all the [available values](https://beets.readthedocs.io/en/stable/reference/pathformat.html#available-values) of the media item combined with _when_ Filetote moves items (after the media item has already moved) leads to a side-effect of Beets trying to get the `filesize` metadata from the old media item's file location. I'll have to dig a bit to see why / if I can avoid that.

**Comment by nrdxp** [comment]
Just hit this as well, it seems to throw annoying errors at the end of the import but is otherwise harmless

**Comment by gtronset** [comment]
@nrdxp @arogl [`v0.4.3` has been released](https://github.com/gtronset/beets-filetote/releases/tag/v0.4.3) and should resolve this warning. Please let me know if you continue to see this warning and I'll reopen.
